---
title: "City Council Legislative Titles in Bargaining Unit and Comparable City Titles"
output:
  html_document:
    theme: cosmo
    toc: true
    toc_depth: 2
    number_sections: true
    highlight: tango
    css: style.css
date: "`r format(Sys.Date(), '%B %d, %Y')`"
bibliography: references.bib
link-citations: true
citeproc: true
nocite: '@*'
editor_options:
  markdown:
    wrap: sentence
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(rprojroot)
root_dir <- find_root(has_file("proposal.Rproj"))
knitr::opts_knit$set(root.dir = root_dir)
```

## Data Scientist
```{r child="code/comparable_salaries/Data_body.Rmd"}
```
## Legislative Policy Analyst
```{r child="code/comparable_salaries/Policy_body.Rmd"}
```

## Legislative Counsel
```{r child="code/comparable_salaries/Counsel_body.Rmd"}
```


## Web Developer
```{r child="code/comparable_salaries/Web_body.Rmd"}
```
## Sources
```{r child="code/comparable_salaries/references.Rmd"}
```
